---
title: "Web technologies"
author: "Claus O. Wilke"
date: "last updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, "Wilke-slides-theme.css"]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: ''
      titleSlideClass: [center, middle]
params:
  cache: TRUE
---

```{r setup, include=FALSE, echo=FALSE, message = FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(comment = "")

library(tidyverse)
library(cowplot)
library(colorspace)
library(here)

# ggplot2 settings so plots scale well for slide size 
theme_set(theme_gray(16)) # 16 for full width, 18 for half width 
update_geom_defaults("point", list(size = 2.0)) # 2 for full width, 2.5 for half width
```

## Anatomy of a web site

--

Web sites consist of three components:

--

- **HTML:** Content of the site

--

- **CSS:** Appearance of the site

--

- **JavaScript:** Interactivity

--

We won't be discussing JavaScript here

---

```{css echo = FALSE}
.html-example {
  padding: 1em;
  border: solid 0.5px black;
}

```

## Block and inline elements

--

`<div>`: Contents stacked vertically

--

`<span>`: Contents placed inline

---

## Block and inline elements

.small-font.pull-left[
HTML input:

```HTML
<div>This</div>
<div>is</div>
<div>an</div>
<div>example</div>
```
]

--

.small-font.pull-right[
Rendered output:

.html-example[
<div>This</div>
<div>is</div>
<div>an</div>
<div>example</div>
]]

--

`<div>` elements are stacked vertically from top to bottom

---

## Block and inline elements

.small-font.pull-left[
HTML input:

```HTML
<span>This</span>
<span>is</span>
<span>an</span>
<span>example</span>
```
]

--

.small-font.pull-right[
Rendered output:

.html-example[
<span>This</span>
<span>is</span>
<span>an</span>
<span>example</span>
]]

--

`<span>` elements are placed inline

---

## Elements can be nested

.small-font.pull-left[
HTML input:

```HTML
<div>
  <span>This</span>
  <span>is</span>
</div>
<div>
  <span>an</span>
  <span>example</span>
<div>
```
]

--

.small-font.pull-right[
Rendered output:

.html-example[
<div>
  <span>This</span>
  <span>is</span>
</div>
<div>
  <span>an</span>
  <span>example</span>
<div>
]]

---

## Elements are styled with CSS

.small-font.pull-left[
HTML input:

```HTML
This is an <span>example</span>
```
]

---

## Elements are styled with CSS

.small-font.pull-left[
HTML input:

```HTML
This is an <span>example</span>
```

CSS input:

```CSS
span { 
  color: #91322F;
  font-weight: bold;
}
```
]

--

.small-font.pull-right[
Rendered output:

.html-example[
This is an <span style = "color: #91322F; font-weight: bold;">example</span>
]]

---

## Elements are styled with CSS

.small-font.pull-left[
HTML input:

```HTML
<div>
This is an <span>example</span>
</div>
```

CSS input:

```CSS
span { color: #91322F; }
div {
  background-color: #D4E1F3;
}
```
]

.small-font.pull-right[
Rendered output:

.html-example[
<div style = "background-color: #D4E1F3;">
This is an <span style = "color: #91322F;">example</span>
</div>
]]



---

## Elements are styled with CSS

.small-font.pull-left[
HTML input:

```HTML
<div>
This is an <span>example</span>
</div>
```

CSS input:

```CSS
span { color: #91322F; }
div {
  background-color: #D4E1F3;
  padding: 36px 8px 24px 8px;
}
```
]

.small-font.pull-right[
Rendered output:

.html-example[
<div style = "background-color: #D4E1F3; padding: 36px 8px 24px 8px;">
This is an <span style = "color: #91322F;">example</span>
</div>
]]

---

## Elements are styled with CSS

.small-font.pull-left[
HTML input:

```HTML
<div>
This is an <span>example</span>
</div>
```

CSS input:

```CSS
span {
  color: #91322F;
  background-color: #D4E1F3;
  padding: 36px 8px 24px 8px;
}
```
]

.pull-right[.small-font[
Rendered output:

.html-example[
<div>
This is an <span style = "color: #91322F; background-color: #D4E1F3; padding: 36px 8px 24px 8px;">example</span>
</div>
]]]


---

## Elements are styled with CSS

.small-font.pull-left[
HTML input:

```HTML
<div>
This is an <span>example</span>
</div>
```

CSS input:

```CSS
span {
  color: #91322F;
  background-color: #D4E1F3;
  padding: 36px 8px 24px 8px;
}
```
]

.small-font.pull-right[
Rendered output:

.html-example[
<div>
This is an <span style = "color: #91322F; background-color: #D4E1F3; padding: 36px 8px 24px 8px;">example</span>
</div>
]

<br>
Top and bottom padding don't affect the height of an inline element
]

---


## Further reading

